server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;

    #access_log  /var/log/nginx/host.access.log  main;

    location / {
        root   /usr/share/nginx/homepage;
        index  index.html;
    }
    
    location /error/ {
        internal;
        root /usr/share/nginx/homepage/src/view;
    }
    
    location /Cyber/ {
        root /usr/share/nginx/homepage/src/view;
        index index.html;
    }

    error_page 400 /error/400.html;
    error_page 401 /error/401.html;
    error_page 404 /error/404.html;
    error_page 500 /error/500.html;
    error_page 502 /error/502.html;

    # deny access to .htaccess files, if Apache's document root
    # concurs with nginx's one
    #
    #location ~ /\.ht {
    #    deny  all;
    #}
}